import Head from 'next/head'

export default function Head_() {
  return (
    <Head>
      <title>ReviewT</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
      {/* <link rel='stylesheet' href='https://fonts.googleapis.com/icon?family=Material+Icons' /> */}
    </Head>
  )
}
