import Head from 'next/head'

export default function Head_() {
  return (
    <Head>
      <title>ReviewT</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
      {/* <link rel='stylesheet' href='https://fonts.googleapis.com/icon?family=Material+Icons' /> */}
      <link
        rel='stylesheet'
        href='https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200'
      />
    </Head>
  )
}
